area/frontend:
  - changed-files:
      - any-glob-to-any-file: ['src/frontend/**']
area/backend:
  - changed-files:
      - any-glob-to-any-file: ['src/backend/**']
area/infra:
  - changed-files:
      - any-glob-to-any-file: ['infra/**']
area/docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']
infra/ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
dependencies:
  - head-branch: ['^dependabot/.*']

