name: "🎨 Sync labels with Max Phan energy"
on:
  push:
    branches: [main]
    paths: [.github/labels.yml]
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout repo (Max style)"
        uses: actions/checkout@v5

      - name: "🔖 Sync all labels — crafted by Max Phan"
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "✅ Labels synced — thanks Max Phan!"
        run: echo "All labels are now aligned perfectly ✨"
